<?php

return [
    'facebook' => [
        'label'                  => 'Facebook',
        'max_text_length'        => 63206,
        'supports_images'        => true,
        'supports_video'         => true,
        'supports_first_comment' => true,
        'supports_link_preview'  => true,
        'max_media_items'        => 10,
        'allowed_media_types'    => ['image/jpeg', 'image/png', 'image/gif', 'video/mp4', 'video/mov'],
        'max_image_size_mb'      => 30,
        'max_video_size_mb'      => 4096,
        'requires_media'         => false,
        'color'                  => '#1877F2',
        'icon'                   => 'facebook',
    ],

    'instagram' => [
        'label'                  => 'Instagram',
        'max_text_length'        => 2200,
        'max_hashtags'           => 30,
        'supports_images'        => true,
        'supports_video'         => true,
        'supports_reels'         => true,
        'supports_carousel'      => true,
        'supports_first_comment' => true,
        'supports_link_preview'  => false,
        'max_media_items'        => 10,
        'allowed_media_types'    => ['image/jpeg', 'image/png', 'video/mp4', 'video/mov'],
        'max_image_size_mb'      => 8,
        'max_video_size_mb'      => 100,
        'requires_media'         => true,
        'color'                  => '#E1306C',
        'icon'                   => 'instagram',
    ],

    'tiktok' => [
        'label'                  => 'TikTok',
        'max_text_length'        => 2200,
        'max_hashtags'           => 100,
        'supports_images'        => false,
        'supports_video'         => true,
        'supports_first_comment' => false,
        'supports_link_preview'  => false,
        'max_media_items'        => 1,
        'allowed_media_types'    => ['video/mp4', 'video/mov', 'video/webm'],
        'max_video_size_mb'      => 4096,
        'min_video_duration_s'   => 3,
        'max_video_duration_s'   => 600,
        'requires_media'         => true,
        'requires_video'         => true,
        'color'                  => '#010101',
        'icon'                   => 'tiktok',
    ],

    'x' => [
        'label'                  => 'X (Twitter)',
        'max_text_length'        => 280,
        'supports_images'        => true,
        'supports_video'         => true,
        'supports_first_comment' => false,
        'supports_link_preview'  => true,
        'max_media_items'        => 4,
        'allowed_media_types'    => ['image/jpeg', 'image/png', 'image/gif', 'video/mp4', 'video/mov'],
        'max_image_size_mb'      => 5,
        'max_video_size_mb'      => 512,
        'requires_media'         => false,
        'color'                  => '#000000',
        'icon'                   => 'x-twitter',
    ],

    'linkedin' => [
        'label'                  => 'LinkedIn',
        'max_text_length'        => 3000,
        'supports_images'        => true,
        'supports_video'         => true,
        'supports_documents'     => true,
        'supports_first_comment' => false,
        'supports_link_preview'  => true,
        'max_media_items'        => 9,
        'allowed_media_types'    => ['image/jpeg', 'image/png', 'image/gif', 'video/mp4', 'application/pdf'],
        'max_image_size_mb'      => 5,
        'max_video_size_mb'      => 5120,
        'requires_media'         => false,
        'color'                  => '#0A66C2',
        'icon'                   => 'linkedin',
    ],
];
